name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Install ChromeDriver
      run: |
        choco install chromedriver --version=114.0.5735.90
        mkdir C:\CommonExePath\
        copy "C:\ProgramData\chocolatey\lib\chromedriver\tools\chromedriver.exe" "C:\CommonExePath\"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
