name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Check Chrome version
      run: google-chrome --version
    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -N https://chromedriver.storage.googleapis.com/128.0.6613.113/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
