name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
    - name: Install ChromeDriver for Chrome 128
      run: |
        sudo apt-get install -y unzip
        wget -N https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.119/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build  --filter "Category!=Selenium" --verbosity normal
